//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfSer_MobData
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CompositeType", Namespace = "http://schemas.datacontract.org/2004/07/WcfSer_MobData")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private bool BoolValueField;

        private string StringValueField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IService_MobData")]
public interface IService_MobData
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService_MobData/GetData", ReplyAction = "http://tempuri.org/IService_MobData/GetDataResponse")]
    string GetData(int value);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService_MobData/GetData", ReplyAction = "http://tempuri.org/IService_MobData/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(int value);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService_MobData/GetDateTime", ReplyAction = "http://tempuri.org/IService_MobData/GetDateTimeResponse")]
    string GetDateTime();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService_MobData/GetDateTime", ReplyAction = "http://tempuri.org/IService_MobData/GetDateTimeResponse")]
    System.Threading.Tasks.Task<string> GetDateTimeAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService_MobData/GetBolusInfo", ReplyAction = "http://tempuri.org/IService_MobData/GetBolusInfoResponse")]
    string GetBolusInfo();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService_MobData/GetBolusInfo", ReplyAction = "http://tempuri.org/IService_MobData/GetBolusInfoResponse")]
    System.Threading.Tasks.Task<string> GetBolusInfoAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService_MobData/GetDataUsingDataContract", ReplyAction = "http://tempuri.org/IService_MobData/GetDataUsingDataContractResponse")]
    WcfSer_MobData.CompositeType GetDataUsingDataContract(WcfSer_MobData.CompositeType composite);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService_MobData/GetDataUsingDataContract", ReplyAction = "http://tempuri.org/IService_MobData/GetDataUsingDataContractResponse")]
    System.Threading.Tasks.Task<WcfSer_MobData.CompositeType> GetDataUsingDataContractAsync(WcfSer_MobData.CompositeType composite);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService_MobDataChannel : IService_MobData, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service_MobDataClient : System.ServiceModel.ClientBase<IService_MobData>, IService_MobData
{

    public Service_MobDataClient()
    {
    }

    public Service_MobDataClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public Service_MobDataClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public Service_MobDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public Service_MobDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }

    public System.Threading.Tasks.Task<string> GetDataAsync(int value)
    {
        return base.Channel.GetDataAsync(value);
    }

    public string GetDateTime()
    {
        return base.Channel.GetDateTime();
    }

    public System.Threading.Tasks.Task<string> GetDateTimeAsync()
    {
        return base.Channel.GetDateTimeAsync();
    }

    public string GetBolusInfo()
    {
        return base.Channel.GetBolusInfo();
    }

    public System.Threading.Tasks.Task<string> GetBolusInfoAsync()
    {
        return base.Channel.GetBolusInfoAsync();
    }

    public WcfSer_MobData.CompositeType GetDataUsingDataContract(WcfSer_MobData.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }

    public System.Threading.Tasks.Task<WcfSer_MobData.CompositeType> GetDataUsingDataContractAsync(WcfSer_MobData.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContractAsync(composite);
    }
}
